### ISSUE TITLE
Agregar un nombre al test

### ISSUE THREAD

**Issue by FabrizioOtranto** [TorreCristianHernan/CrisEntrega-#7]
https://github.com/TorreCristianHernan/CrisEntrega-/blob/e1246539cfb2402cad80ae4236159e3eae98d242/cypress/e2e/Entregafinal.cy.js#L37

**Comment by TorreCristianHernan** [comment]
Profe no se olvide de enviarme el certificado porfavor asi lo agrego a los
que ya tengo
Aprendi muchisimo super agradecido!!!
